# Generated by Django 5.2.6 on 2026-10-03 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_sale_invoice_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='final_price',
        ),
    ]
