# Generated by Django 5.2.6 on 2026-10-05 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_product_sale_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ledger_suppliers',
                'indexes': [models.Index(fields=['name'], name='ledger_supp_name_153b60_idx')],
            },
        ),
        migrations.CreateModel(
            name='LedgerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='inventory.ledgersupplier')),
            ],
            options={
                'db_table': 'ledger_invoices',
            },
        ),
        migrations.CreateModel(
            name='LedgerInvoiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.ledgerinvoice')),
            ],
            options={
                'db_table': 'ledger_invoice_images',
                'indexes': [models.Index(fields=['invoice_id', 'order'], name='ledger_invo_invoice_8f8ba7_idx')],
            },
        ),
        migrations.CreateModel(
            name='LedgerLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_name', models.CharField(max_length=200)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.FloatField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.ledgerinvoice')),
            ],
            options={
                'db_table': 'ledger_lines',
                'indexes': [models.Index(fields=['invoice_id', 'id'], name='ledger_line_invoice_2d4a07_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ledgerinvoice',
            index=models.Index(fields=['supplier_id', '-id'], name='ledger_invo_supplie_ec7fc8_idx'),
        ),
    ]
